#+TITLE: Dai-gokyo (Group 5) - Documentation

* Basics
assignment is done using the ~<-~ operator

~x <- 10~

vectors are created with the ~c()~ method

~x <- c(3, 5, 7)~

if you perform an expression on a vector it applies that expression to each
element in the vector and returns a new vector with those values

#+BEGIN_SRC R
x <- c(3, 5, 7)
x + 1
=>[4, 6, 8]
#+END_SRC

What is actually happening here is a vector operation and in order to do this
R casts the 1 in the addition to a vector of 1's in order to be able to do
the calculation

#+BEGIN_SRC R
# What happens behind the scenes
x <- c(3, 5, 7)
x + 1
[3, 5, 7] + [1, 1, 1]
=>[4, 6, 8]
#+END_SRC

If you add to different size vectors the smaller vector is repeated until
it is the same size of the larger vector.

If the vectors aren't wholly divisible the operation will still happen but
R will give a warning letting you know.

#+BEGIN_SRC R
c(1, 2, 3) + c(1,2)
[1] 2 4 4
Warning message:
In c(1, 2, 3) + c(1, 2) :
  longer object length is not a multiple of shorter object length
#+END_SRC

** HELP
The following methods are useful for finding help in R

~help()~ or its alias ~?~

using ~?~ will pull up the help documentation for the method in question.
If the method being queried is a keyword then it will need to be quoted.

#+BEGIN_SRC R
?lapply
# however these need quotes
?'for'
?'?'
?'??'
#+END_SRC
 
~help.search()~ or its alias ~??~

Using ~??~ will search the documentation for all help that has the search
term in its content and return a list of search topics that match.

* Workspace and Files
~getwd()~ returns the current working directory

~ls()~ will list all objects in your current workspace.

~dir()~ or ~list.files()~ will show the files in your current working
directory.

~args(fn)~ will tell you what arguments fn takes.

~dir.create(dirname)~ will create a directory with dirname. This is useful
for creating a temporary work area to be cleaned up later.

~setwd(dirname)~ sets the current working directory to dirname.

~file.create(filename)~ will create a file named filename.

~file.exists(filename)~ returns TRUE if filename exists.

~file.info(filename)~ returns detailed information on a file. You can use the
'$' vector operator to access specific information ~file.info(filename)$mode~

~file.rename(from, to)~ will rename a file.

~file.copy(from, to)~ will copy a file.

~file.path()~ will create a platform dependent filepath from the arguments.

You can chain commands together. To create a nested directory you will need
to pass the ~recursive = TRUE~ to ~dir.create()~
#+BEGIN_SRC R
dir.create(file.path('testdir2', 'testdir3'), recursive = TRUE)
# equivalent to mkdir -p testdir2/testdir3
#+END_SRC

~unlink()~ will delete a file or directory. If you need to remove a directory,
and by association all its contents, you need to let R know this is your
intention. You do this by passing in ~recursive = TRUE~ to the function.

* Subsetting and Vectors

Subsetting is selecting the parts of a vector you are interested in.

*** Key Point
To subset you pass in a vector of the elements you want

The vectors you can pass in come in four flavours
- logical vectors
- vectors of positive integers
- vectors of negative integers
- vectors of character strings

** Logical Vectors
True and False act as a mask where only the TRUE vals show through.

=is.na(x)=
will give a vector where all NA values are True.

By using the not operator (!) you can reverse this and get only elements that
have a value.

=x[!is.na(x)]=

we can subset on other conditions using boolean logic.

=x[x>6]=

The above examples can be combined.

=x[!is.na(x) & x > 6]=

*** In R vectors are 1 based
Remember in R vectors are 1 based and not zero based.

You are responsible for ensuring that the index of the vector you access
exists.

If you go below the bounds you get a numeric(0) value

if you go above the bound you get an NA value

eg. for x <- 1:10

=x[0] => numeric(0)=

=x[11] => NA=

** Vectors of positive integers
Passing in a vector of positive integers allows you to pass in non contigous
indices.

eg. to select the 3rd, 5th and 7th vector

=x[c(3, 5, 7)]=

** Vectors of negative integers
If you want all items of a vector except a few you can pass in a negative
vector of all the indices you don't want.

eg. to get all items of a vector except the 2nd and 10th element

=x[c(-2, -10)]=

alternatively you can put the - in front of the call to combine(); this will
apply the - operator to each element in the vector

=x[-c(2, 10)]=

** Vectors of character strings
If a vector is named we can access the values we want by passing in a
vector of names.

We can see if a vector has names by using the names function.

=names(vect)=

If it doesn't we can give the vector names if we want to.

=names(vect) <- c("foo", "bar", "baz")=

Then we can access the vector using a vector of character strings

=vect[c("foo", "baz")]=

* Matrices and Data Frames

Matrices contain a single type of data.

Data Frames can contain mixed data.

Another way of thinking about this is that a matrix is a vector of vectors,
but a data frame is a vector of lists.

A matrix is just a vector with dimensions

=my_vector <- 1:20=

=length(my_vector)             => 20=

=dim(my_vector)                => NULL=

=dim(my_vector) <- c(4, 5)=

=class(my_vector)              => Matrix=

you can also see the dim property using the =attributes()= function

Matrices are declared by row then column.
You can create a matrix directly using the =matrix()= function

=matrix(1:20, 4, 5)=

You can use the =cbind()= function to add an additional column to a matrix
where the column to be added is a vector.

=cbind(vector_col, matrix)=

Using cbind on a matrix with different data types will cause the new matrix
to be cast to a data type that is common to both the column being added and
the old matrix. This is usually a character string.

To keep both items as their original data type, use a data frame.

=data.frame(vector_col, matrix)=

data.frame can take as many arguments as items needed to be joined.

You can assign names to the data frame columns by passing in a vector of
names ot the =colnames()= function.

=colnames(my_data) <- c("col1", "col2", "col3")=

* Logic
R has the usual logic values TRUE, FALSE, ==, !=, <, <=, >, >=

** OR
Or can be in the form of =|= or =||=

The singular operates over each element of the vector returning a vector of
booleans.

The double bar returns a result based on an or operation of the first vector
element only.

** And
And can be in the form of =&= or =&&=

The singular operates over each element of the vector returning a vector of
booleans.

The double ampersand returns a result based on an and operation of the 
first vector element only.

** Addtional Functions
=isTRUE()= takes one argument and if it is true returns true otherwise returns
false.

=indentical()= checks two object for exaxt Equality.

=xor()= will xor its arguments.

=which()= returns a vector of indices for which the expression holds true

~which(x <= 2)~ # returns a vector of indices where the vector x is less than
or equal to two.

=any()= returns true if any of the elements in the vector expression is true.

=all()= returns true if all of the elelement in the vector expression are true.


