#+TITLE: Manipulating data with tidyr

Information set out here is heavily borrowed from the Swirl package
Getting and Cleaning Data.

* Each Column should be a variable

For clean data each column should be a distince variable.
Examples include sex, count

The following represents unclean data.

#+BEGIN_SRC TXT
  grade male female
1     A    1      5
2     B    5      0
3     C    5      2
4     D    5      5
5     E    7      4
#+END_SRC

The reason for this is that is that the male and females columns should
be just a single column "sex" and an additional column called count
should give a number dimension to these.

In many ways this is similar to denormalizing data in a database.

** Gather

Using ~gather()~ can help fix the data

#+BEGIN_SRC R
gather(data_frame, sex, count -grade)

# gather takes a
# - data frame
# - key
# - vaule
# - list of columns to collapse into key / value pairs

# passing in -grade collapse all columns except grade ie.
# sex and count

# the resulting output is.

   grade    sex count
1      A   male     1
2      B   male     5
3      C   male     5
4      D   male     5
5      E   male     7
6      A female     5
7      B female     0
8      C female     2
9      D female     5
10     E female     4
#+END_SRC

* Multiple values in one column

Look at the following dataset

#+BEGIN_SRC TXT
  grade male_1 female_1 male_2 female_2
1     A      3        4      3        4
2     B      6        4      3        5
3     C      7        4      3        8
4     D      4        0      8        1
5     E      1        1      2        7
#+END_SRC

This dataset is similar to the first, except now there are two separate
classes, 1 and 2, and we have total counts for each sex within each class.
The data frame suffers from the same messy data problem of having column
headers that are values (male_1, female_1, etc.) and not variable names
(sex, class, and count).              |

However, it also has multiple variables stored in each column (sex and class),
which is another common symptom of messy data. Tidying this dataset will be a
two step process.

The first stage to fixing this data is to unite the classes and sexes into
a single column

#+BEGIN_SRC R
gather(data_frame, sex_class, count, -grade)

   grade sex_class count
1      A    male_1     3
2      B    male_1     6
3      C    male_1     7
4      D    male_1     4
5      E    male_1     1
6      A  female_1     4
7      B  female_1     4
8      C  female_1     4
9      D  female_1     0
10     E  female_1     1
11     A    male_2     3
12     B    male_2     3
13     C    male_2     3
14     D    male_2     8
15     E    male_2     2
16     A  female_2     4
17     B  female_2     5
18     C  female_2     8
19     D  female_2     1
20     E  female_2     7
#+END_SRC

** Separate

The sex_class column still holds two variables, sex and class.
We can use the ~separate()~ function to convert this column into multiples
columns of single variables.

~separate()~ separates data by splitting on non alphanumeric characters but
you can pass in a regex if you need to change this behaviour. For more
information see ~?gather~.

#+BEGIN_SRC R
# separate takes the following arguments
# - the data frame
# - the column to split
# - a vector of columns to split the data into

# calling separate on the data above gives us

separate(res, sex_class, c("sex", "class"))

   grade    sex class count
1      A   male     1     3
2      B   male     1     6
3      C   male     1     7
4      D   male     1     4
5      E   male     1     1
6      A female     1     4
7      B female     1     4
8      C female     1     4
9      D female     1     0
10     E female     1     1
11     A   male     2     3
12     B   male     2     3
13     C   male     2     3
14     D   male     2     8
15     E   male     2     2
16     A female     2     4
17     B female     2     5
18     C female     2     8
19     D female     2     1
20     E female     2     7
#+END_SRC

** Chaining with %>%

In order to prevent having to create an intermediate variable for the two
stage process above we can use the ~%>%~ operator to chain the process and
get the same result.

#+BEGIN_SRC R
data_frame %>%
  gather( sex_class, count, -grade ) %>%
  separate( sex_class, c("sex", "class")) %>%
  print
#+END_SRC

* Variables across rows and columns

A third symptom of messy data is when variables are stored in both rows and
columns. The following data frame provides an example of this.

#+BEGIN_SRC
    name    test class1 class2 class3 class4 class5
1  Sally midterm      A   <NA>      B   <NA>   <NA>
2  Sally   final      C   <NA>      C   <NA>   <NA>
3   Jeff midterm   <NA>      D   <NA>      A   <NA>
4   Jeff   final   <NA>      E   <NA>      C   <NA>
5  Roger midterm   <NA>      C   <NA>   <NA>      B
6  Roger   final   <NA>      A   <NA>   <NA>      A
7  Karen midterm   <NA>   <NA>      C      A   <NA>
8  Karen   final   <NA>   <NA>      C      A   <NA>
9  Brian midterm      B   <NA>   <NA>   <NA>      A
10 Brian   final      B   <NA>   <NA>   <NA>      C
#+END_SRC

The first variable, name, is already a column and should remain as it is.
The headers of the last five columns, class1 through class5, are all different
values of what should be a class variable. The values in the test column,
midterm and final, should each be its own variable containing the respective
grades for each student.

The first stage is to gather class1 through class5 into a variable,
discarding any rows that would have NA's in them.

#+BEGIN_SRC
my_data_frame %>%
  gather( class, grade, class1:class5 , na.rm = TRUE) %>%
  print

    name    test  class grade
1  Sally midterm class1     A
2  Sally   final class1     C
3  Brian midterm class1     B
4  Brian   final class1     B
5   Jeff midterm class2     D
6   Jeff   final class2     E
7  Roger midterm class2     C
8  Roger   final class2     A
9  Sally midterm class3     B
10 Sally   final class3     C
11 Karen midterm class3     C
12 Karen   final class3     C
13  Jeff midterm class4     A
14  Jeff   final class4     C
15 Karen midterm class4     A
16 Karen   final class4     A
17 Roger midterm class5     B
18 Roger   final class5     A
19 Brian midterm class5     A
20 Brian   final class5     C
#+END_SRC

The next stage involves making the values in the test column variables that have
the grade as their value. This can be done with the ~spread()~ function.

#+BEGIN_SRC R
my_data_frame %>%
  gather(class, grade, class1:class5, na.rm = TRUE) %>%
  spread(test , grade) %>%
  print

    name  class final midterm
1  Brian class1     B       B
2  Brian class5     C       A
3   Jeff class2     E       D
4   Jeff class4     C       A
5  Karen class3     C       C
6  Karen class4     A       A
7  Roger class2     A       C
8  Roger class5     A       B
9  Sally class1     C       A
10 Sally class3     C       B
#+END_SRC

Finally we want to remove the class prefix from the values in the class
column. This can be done with the ~mutate()~ and ~extract_numeric()~ functions.

#+BEGIN_SRC R
my_data_frame %>%
  gather(class, grade, class1:class5, na.rm = TRUE) %>%
  spread(test, grade) %>%
  mutate(class = extract_numeric(class)) %>%
  print

    name class final midterm
1  Brian     1     B       B
2  Brian     5     C       A
3   Jeff     2     E       D
4   Jeff     4     C       A
5  Karen     3     C       C
6  Karen     4     A       A
7  Roger     2     A       C
8  Roger     5     A       B
9  Sally     1     C       A
10 Sally     3     C       B
#+END_SRC

* Multi Observational Units in the same table

#+BEGIN_SRC R
    id  name sex class midterm final
1  168 Brian   F     1       B     B
2  168 Brian   F     5       A     C
3  588 Sally   M     1       A     C
4  588 Sally   M     3       B     C
5  710  Jeff   M     2       D     E
6  710  Jeff   M     4       A     C
7  731 Roger   F     2       C     A
8  731 Roger   F     5       B     A
9  908 Karen   M     3       C     C
10 908 Karen   M     4       A     A
#+END_SRC

The data above is an example of having multi observational units in the same
table. Each student has a unique id as well as his or her sex.

A hint that this problem exists is when data is repeated. In the data above
some names and sex data are repeated when only the id is needed.

This data can be split into two data frames to normalise the data.

#+BEGIN_SRC R
# Pulling out id, name and sex requires a select that is piped through
# unique to remove duplicates.

student_info <- my_data_frame %>%
  select(id, name, sex) %>%
  unique() %>%
  print

   id  name sex
1 168 Brian   F
3 588 Sally   M
5 710  Jeff   M
7 731 Roger   F
9 908 Karen   M

# The other columns are unique elements so just need selected into a new
# data frame

gradebook <- my_data_frame %>%
  select(id, class, midterm, final) %>%
  print

    id class midterm final
1  168     1       B     B
2  168     5       A     C
3  588     1       A     C
4  588     3       B     C
5  710     2       D     E
6  710     4       A     C
7  731     2       C     A
8  731     5       B     A
9  908     3       C     C
10 908     4       A     A
#+END_SRC

Relational theory still applies so, as we would with a database, we need a
column to tie the two tables together. In this case it is the id column.

* Observational units across multiple tables

Look at the following two dataframes

#+BEGIN_SRC R
> passed
   name class final
1 Brian     1     B
2 Roger     2     A
3 Roger     5     A
4 Karen     4     A

> failed
   name class final
1 Brian     5     C
2 Sally     1     C
3 Sally     3     C
4  Jeff     2     E
5  Jeff     4     C
6 Karen     3     C
#+END_SRC

Teachers decided to only take into consideration final exam grades in
determining whether students passed or failed each class. Students
fail if the received a C or lower.

The name of each data set, passed and failed, represents the value of
a variable we will call status. Before joining the tables together we
will add a column containing this information so that it is not lost
when we join the tables.

#+BEGIN_SRC R
passed <- mutate(passed, status="passed")
#or
passed <- passed %>% mutate(status = "passed")

failed <- mutate(failed, status="passed")
#or
failed <- failed %>% mutate(status = "failed")
#+END_SRC

To perform a union on two data frames use the ~bind_rows()~ function.

#+BEGIN_SRC
bind_rows(passed, failed)

    name class final status
1  Brian     1     B passed
2  Roger     2     A passed
3  Roger     5     A passed
4  Karen     4     A passed
5  Brian     5     C failed
6  Sally     1     C failed
7  Sally     3     C failed
8   Jeff     2     E failed
9   Jeff     4     C failed
10 Karen     3     C failed
#+END_SRC

* Final Example

Look at the data set below for american sat results obtained from
http://research.collegeboard.org/programs/sat/data/cb-seniors-2013

#+BEGIN_SRC R
> sat
Source: local data frame [6 x 10]

  score_range read_male read_fem read_total math_male math_fem math_total write_male write_fem write_total
1     700-800     40151    38898      79049     74461    46040     120501      31574     39101       70675
2     600-690    121950   126084     248034    162564   133954     296518     100963    125368      226331
3     500-590    227141   259553     486694    233141   257678     490819     202326    247239      449565
4     400-490    242554   296793     539347    204670   288696     493366     262623    302933      565556
5     300-390    113568   133473     247041     82468   131025     213493     146106    144381      290487
6     200-290     30728    29154      59882     18788    26562      45350      32500     24933       57433
...
#+END_SRC

firs we remove the totals as they can be added back later as a
calculated column

#+BEGIN_SRC R
> sat %>%
+     select(-contains("total")) %>%
+     print

  score_range read_male read_fem math_male math_fem write_male write_fem
1     700-800     40151    38898     74461    46040      31574     39101
2     600-690    121950   126084    162564   133954     100963    125368
3     500-590    227141   259553    233141   257678     202326    247239
4     400-490    242554   296793    204670   288696     262623    302933
5     300-390    113568   133473     82468   131025     146106    144381
6     200-290     30728    29154     18788    26562      32500     24933
...
#+END_SRC

Then we need to split up all the columns into part and sex with the
exception of score_range.

#+BEGIN_SRC R
> sat %>%
+     select(-contains("total")) %>%
+     gather(part_sex, count, -score_range) %>%
+     print

   score_range  part_sex  count
1      700-800 read_male  40151
2      600-690 read_male 121950
3      500-590 read_male 227141
4      400-490 read_male 242554
5      300-390 read_male 113568
6      200-290 read_male  30728
7      700-800  read_fem  38898
8      600-690  read_fem 126084
9      500-590  read_fem 259553
10     400-490  read_fem 296793
..         ...       ...    ...
#+END_SRC

Then we separate the part_sex column into part and sex.

#+BEGIN_SRC R
sat %>%
  select(-contains("total")) %>%
  gather(part_sex, count, -score_range) %>%
  separate(part_sex, c("part", "sex")) %>%
  print

   score_range part  sex  count
1      700-800 read male  40151
2      600-690 read male 121950
3      500-590 read male 227141
4      400-490 read male 242554
5      300-390 read male 113568
6      200-290 read male  30728
7      700-800 read  fem  38898
8      600-690 read  fem 126084
9      500-590 read  fem 259553
10     400-490 read  fem 296793
..         ...  ...  ...    ...
#+END_SRC

Then we group the data set into part and sex

#+BEGIN_SRC R
sat %>%
  select(-contains("total")) %>%
  gather(part_sex, count, -score_range) %>%
  separate(part_sex, c("part", "sex")) %>%
  group_by(part, sex) %>%
  print

   score_range part  sex  count
1      700-800 read male  40151
2      600-690 read male 121950
3      500-590 read male 227141
4      400-490 read male 242554
5      300-390 read male 113568
6      200-290 read male  30728
7      700-800 read  fem  38898
8      600-690 read  fem 126084
9      500-590 read  fem 259553
10     400-490 read  fem 296793
..         ...  ...  ...    ...
#+END_SRC

Finally we can add two calculated variables to our data set.

#+BEGIN_SRC R
sat %>%
  select(-contains("total")) %>%
  gather(part_sex, count, -score_range) %>%
  separate(part_sex, c("part", "sex")) %>%
  group_by(part, sex) %>%
  mutate(total = sum(count),
         prop = count / total) %>% 
  print

   score_range part  sex  count  total       prop
1      700-800 read male  40151 776092 0.05173485
2      600-690 read male 121950 776092 0.15713343
3      500-590 read male 227141 776092 0.29267278
4      400-490 read male 242554 776092 0.31253253
5      300-390 read male 113568 776092 0.14633317
6      200-290 read male  30728 776092 0.03959324
7      700-800 read  fem  38898 883955 0.04400450
8      600-690 read  fem 126084 883955 0.14263622
9      500-590 read  fem 259553 883955 0.29362694
10     400-490 read  fem 296793 883955 0.33575578
..         ...  ...  ...    ...    ...        ...
#+END_SRC
